article:
  path:     /{_locale}/article/{date}/{slug}.{_format}
  defaults: { option: com_articles, view: article, _format: html }
  requirements:
    date: "[a-zA-Z0-9-_/]+"
    slug: "[a-zA-Z0-9-_/]+"
articles:
  path:     /{_locale}/articles.{_format}
  defaults: { option: com_articles, view: article, _format: html }